/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./site/**/*.{html,js,lr}", "./site/**/*.html"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1rem",
        lg: "2rem",
        xl: "2rem",
        "2xl": "3rem",
        // "3xl": "3rem",
        // "3xl": "4rem",
      },
    },

    extend: {
      colors: {
        black: "#27272a",
        white: "#fafafa",
        tonered: "#e88b8b",
        toneorange: "#ee4d02",
        toneyellow: "#e8cc70",
        tonegreen: "#4fef94",
        toneblue: "#02a2ee",
        tonepink: "#ef4faA",
        toneviolet: "#d602ee",
        tonebrown: "#796456",
        fullred: "#ef4f5a",
        fullorange: "#f4891d",
        fullyellow: "#eace29",
        fullgreen: "#09a44f",
        fullblue: "#44a0e3",
        fullpink: "#d8098e",
        fullviolet: "#e44fef",
        fullbrown: "#68310d",
        tintred: "#f4b6b6",
        tintorange: "#ef944f",
        tintyellow: "#f2e1a3",
        tintgreen: "#a8d5b8",
        tintblue: "#add8f0",
        tintpink: "#e6a6c9",
        tintviolet: "#c7a6d8",
        tintbrown: "#a7856e",
        color1: "#6002ee",
        color2: "#d602ee",
        color3: "#bc5090",
        color4: "#ff6361",
        color5: "#ffa600",
        colorgrey: "#333333",
      },
      screens: {
        // "3xl": "1900px",
        // "4xl": "2600px",
      },
      borderRadius: {
        big: "42px",
        huge: "128px",
        circle: "50%",
      },
      fontFamily: {
        sans: ['"Inter"', "sans-serif"],
        body: ['"Inter"', "sans-serif"],
        // display: ['"Red Hat Display"', "sans-serif"],
        display: ['"Inter"', "sans-serif"],
        mono: ["ui-monospace", "monospace"],
      },

      fontSize: {
        sm: ["0.875rem", { lineHeight: "1.375" }], // `leading-snug`
        base: ["1rem", { lineHeight: "1.375" }],
        lg: ["1.125rem", { lineHeight: "1.375" }],
        xl: ["1.25rem", { lineHeight: "1.375" }],
        "2xl": ["1.5rem", { lineHeight: "1.375" }],
        "3xl": ["1.875rem", { lineHeight: "1.375" }],
        "4xl": ["2.25rem", { lineHeight: "1.375" }],
        "5xl": ["3rem", { lineHeight: "1.375" }],
        "6xl": ["3.75rem", { lineHeight: "1.375" }],
        "7xl": ["4.5rem", { lineHeight: "1.375" }],
        "8xl": ["6rem", { lineHeight: "1.375" }],
        "9xl": ["8rem", { lineHeight: "1.375" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("daisyui"),
    require("tailwindcss-animate"),
  ],
  daisyui: {
    logs: true,
    themes: false,
    themes: [
      {
        mytheme: {
          primary: "#58508d",
          secondary: "#58508d",
          accent: "#bc5090",
          neutral: "#58508d",
          "base-100": "#ffffff",
          info: "#5a6fb6",
          success: "#84cc16",
          warning: "#ffa600",
          error: "#ff6e54",
        },
      },
      "dark",
      "corporate",
    ],
  },
};
